version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgresql/schema:/docker-entrypoint-initdb.d
      - ./postgresql/pgdata:/var/lib/postgresql/data

  hotel-search:
    build: ./hotels-search-service/hotels-search
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./hotels-search-service/hotels-search/:/app
  
  user-service:
    build: ./user-service/user-service
    depends_on:
      - db
    ports:
      - "8081:8081"
    volumes:
      - ./user-service/user-service/:/app