version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresql/schema:/docker-entrypoint-initdb.d
      - ./postgresql/pgdata:/var/lib/postgresql/data
    env_file:
      - ./postgresql/.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - ./postgresql/.env
  hotel-search:
    build: ./hotels-search-service/hotels-search
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./hotels-search-service/hotels-search/:/app
    env_file:
      - ./hotels-search-service/.env
  user-service:
    build: ./user-service/user-service
    depends_on:
      - db
    ports:
      - "8081:8080"
    volumes:
      - ./user-service/user-service/:/app
    env_file:
      - ./user-service/.env
  notification-service:
    build: ./notification-service/notification-service
    depends_on:
      - db
    ports:
      - "8082:8080"
    volumes:
      - ./notification-service/notification-service/:/app
    env_file:
      - ./notification-service/.env
