version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgresql/schema:/docker-entrypoint-initdb.d
      - ./postgresql/pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "cychiu8@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
  hotel-search:
    build: ./hotels-search-service/hotels-search
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./hotels-search-service/hotels-search/:/app
  
  user-service:
    build: ./user-service/user-service
    depends_on:
      - db
    ports:
      - "8081:8080"
    volumes:
      - ./user-service/user-service/:/app